<template>
  <div class="legal-page">
    <NavBar />
    
    <div class="container">
      <div class="legal-content">
        <h1>Terms of Service</h1>
        <p class="last-updated">Last updated: January 6, 2026</p>
        
        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using Oricode AI ("Service"), you agree to be bound by these 
            Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.
          </p>
        </section>
        
        <section>
          <h2>2. Description of Service</h2>
          <p>
            Oricode AI provides an AI-powered coding assistant for SAP ABAP development, 
            including but not limited to:
          </p>
          <ul>
            <li>AI chat assistance via Eclipse ADT plugin</li>
            <li>Code generation and explanation</li>
            <li>SAP object reading and modification (MCP)</li>
            <li>API access for integrations</li>
          </ul>
        </section>
        
        <section>
          <h2>3. Account Registration</h2>
          <p>
            To use the Service, you must create an account. You agree to:
          </p>
          <ul>
            <li>Provide accurate and complete information</li>
            <li>Maintain the security of your account credentials</li>
            <li>Notify us immediately of any unauthorized access</li>
            <li>Accept responsibility for all activities under your account</li>
          </ul>
        </section>
        
        <section>
          <h2>4. Subscription and Payments</h2>
          
          <h3>4.1 Plans and Pricing</h3>
          <p>
            We offer various subscription plans (Free, Pro, Team, Enterprise). 
            Pricing and features are subject to change with notice.
          </p>
          
          <h3>4.2 Billing</h3>
          <p>
            Paid subscriptions are billed in advance on a monthly or annual basis. 
            All payments are processed by Stripe and are non-refundable unless 
            required by law.
          </p>
          
          <h3>4.3 Credits</h3>
          <p>
            Some features consume credits. Unused credits do not roll over between 
            billing periods unless specified in your plan.
          </p>
        </section>
        
        <section>
          <h2>5. Acceptable Use</h2>
          <p>You agree NOT to:</p>
          <ul>
            <li>Use the Service for any illegal purpose</li>
            <li>Attempt to reverse engineer or extract our AI models</li>
            <li>Share your API key with unauthorized parties</li>
            <li>Generate malicious code or security exploits</li>
            <li>Overload or disrupt the Service infrastructure</li>
            <li>Resell or redistribute the Service without permission</li>
            <li>Use the Service to compete directly with Oricode AI</li>
          </ul>
        </section>
        
        <section>
          <h2>6. Intellectual Property</h2>
          
          <h3>6.1 Our IP</h3>
          <p>
            The Service, including all software, designs, and content, is owned by 
            Oricode AI and protected by intellectual property laws. You receive a 
            limited, non-exclusive license to use the Service.
          </p>
          
          <h3>6.2 Your Code</h3>
          <p>
            You retain ownership of any code you create using our Service. 
            By using the Service, you grant us a limited license to process 
            your code for the purpose of providing AI assistance.
          </p>
          
          <h3>6.3 AI-Generated Content</h3>
          <p>
            Code and content generated by our AI assistant is provided for your use. 
            You are responsible for reviewing and testing any generated code before 
            using it in production systems.
          </p>
        </section>
        
        <section>
          <h2>7. SAP and Third-Party Systems</h2>
          <p>
            When using MCP features to interact with SAP systems:
          </p>
          <ul>
            <li>You are responsible for having proper authorization to access those systems</li>
            <li>You accept all risks associated with modifying SAP objects</li>
            <li>We are not responsible for any damage to your SAP systems</li>
            <li>SAP is a trademark of SAP SE; we are not affiliated with SAP</li>
          </ul>
        </section>
        
        <section>
          <h2>8. Disclaimer of Warranties</h2>
          <p>
            THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS 
            OR IMPLIED. WE DO NOT GUARANTEE THAT:
          </p>
          <ul>
            <li>The Service will be uninterrupted or error-free</li>
            <li>AI-generated code will be correct, secure, or fit for purpose</li>
            <li>The Service will meet your specific requirements</li>
          </ul>
        </section>
        
        <section>
          <h2>9. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, ORICODE AI SHALL NOT BE LIABLE 
            FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, 
            INCLUDING BUT NOT LIMITED TO:
          </p>
          <ul>
            <li>Loss of profits or revenue</li>
            <li>Loss of data</li>
            <li>Business interruption</li>
            <li>Damage to SAP or other systems</li>
          </ul>
          <p>
            Our total liability shall not exceed the amount paid by you in the 
            twelve (12) months preceding the claim.
          </p>
        </section>
        
        <section>
          <h2>10. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless Oricode AI from any claims, 
            damages, or expenses arising from your use of the Service or violation 
            of these Terms.
          </p>
        </section>
        
        <section>
          <h2>11. Termination</h2>
          <p>
            We may suspend or terminate your account at any time for violation of 
            these Terms. Upon termination:
          </p>
          <ul>
            <li>Your right to use the Service ceases immediately</li>
            <li>We may delete your data after a reasonable period</li>
            <li>Provisions that should survive termination will remain in effect</li>
          </ul>
        </section>
        
        <section>
          <h2>12. Changes to Terms</h2>
          <p>
            We may modify these Terms at any time. Continued use of the Service 
            after changes constitutes acceptance of the new Terms. We will notify 
            you of material changes via email or in-app notification.
          </p>
        </section>
        
        <section>
          <h2>13. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the State of Delaware, United States, 
            without regard to conflict of law principles.
          </p>
        </section>
        
        <section>
          <h2>14. Dispute Resolution</h2>
          <p>
            Any disputes arising from these Terms or the Service shall be resolved 
            through binding arbitration in accordance with the rules of the American 
            Arbitration Association.
          </p>
        </section>
        
        <section>
          <h2>15. Contact</h2>
          <p>
            For questions about these Terms, please contact us at:
          </p>
          <p>
            <strong>Email:</strong> <a href="mailto:support@oricode.ai">support@oricode.ai</a>
          </p>
        </section>
      </div>
    </div>
    
    <FooterSection />
  </div>
</template>

<script setup>
useHead({
  title: 'Terms of Service - Oricode AI'
})
</script>

<style scoped>
.legal-page {
  min-height: 100vh;
  background: var(--slate-950);
}

.legal-content {
  max-width: 800px;
  margin: 0 auto;
  padding: 120px 2rem 4rem;
}

h1 {
  font-size: 2.5rem;
  color: var(--slate-100);
  margin-bottom: 0.5rem;
}

.last-updated {
  color: var(--slate-500);
  font-size: 0.9rem;
  margin-bottom: 3rem;
}

section {
  margin-bottom: 2.5rem;
}

h2 {
  font-size: 1.5rem;
  color: var(--slate-100);
  margin-bottom: 1rem;
  padding-bottom: 0.5rem;
  border-bottom: 1px solid var(--slate-800);
}

h3 {
  font-size: 1.1rem;
  color: var(--slate-200);
  margin: 1.5rem 0 0.75rem;
}

p {
  color: var(--slate-400);
  line-height: 1.8;
  margin-bottom: 1rem;
}

ul {
  color: var(--slate-400);
  line-height: 1.8;
  margin-left: 1.5rem;
  margin-bottom: 1rem;
}

li {
  margin-bottom: 0.5rem;
}

a {
  color: var(--orange-500);
}

a:hover {
  text-decoration: underline;
}

strong {
  color: var(--slate-300);
}
</style>
